### PR TITLE
Move error handling to C code

### LINKED ISSUE #231: Error handling is not thead-safe
We use [ERR_get_error](https://docs.openssl.org/3.3/man3/ERR_get_error/#synopsis) to retrieve the error that caused a given function call to fail. This function docs says this:

> ERR_get_error() returns the earliest error code from the thread's error queue and removes the entry. 

The problem is that cgo calls can be rescheduled on any thread when switching back from the system stack to the goroutine stack, The Go scheduler does this to avoid goroutines having to wait for the original thread to be available.

This means that our call to `ERR_get_error` might not return the correct error, or even no error at all.

There are two ways to solve this:

- Calling `runtime.LockOSThread` and `defer runtime.UnlockOSThread` before every cgo call so that the goroutine is always recheduled to the same thread.
- Replacing all OpenSSL cgo calls for a custom C wrapper function that calls the OpenSSL C function and also `ERR_get_error` if that fails. Note that this will work because a goroutine can't be rescheduled while in the system stack.

The first option is the easiest one, but will impact the performance of our OpenSSL backend even in the no-error cases. I would prefer to investigate how we could implement the second option, which wouldn't have any performance impact. Note that both options will require big refactors, as we will need to wrap existing cgo calls into either a C or a Go function (or even both).

### PR DESCRIPTION
**Pull request by qmuntal**
This PR moves most of the error handling to the C side so that we don't have to worry about us retrieving OpenSSL errors from the wrong OpenSSL per-thread error queue (see #231).

The main trick is to autogenerate a new set of C wrappers, for those functions that return an error, with an additional error parameter that will be filled with error context if the function fails. The Go autogenerated functions will convert that error context into a Go error and return it to the caller.

This new error handling approach should have 0 performance impact when there are no errors. In the error situation, expect less allocations thanks to some small improvements I've done to the C ->Go error mapping process:

```
goos: windows
goarch: amd64
pkg: github.com/golang-fips/openssl/v2
cpu: Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
         │   old.txt   │               new.txt               │
         │   sec/op    │    sec/op     vs base               │
Error-12   5.035µ ± 1%   4.685µ ± 13%  -6.96% (p=0.019 n=10)

         │   old.txt    │               new.txt                │
         │     B/op     │     B/op      vs base                │
Error-12   2.184Ki ± 0%   1.537Ki ± 0%  -29.61% (p=0.000 n=10)

         │  old.txt   │              new.txt               │
         │ allocs/op  │ allocs/op   vs base                │
Error-12   20.00 ± 0%   10.00 ± 0%  -50.00% (p=0.000 n=10)
```

Note that this PR almost only changes `mkcgo` and autogenerated code, as #262 already did the job of refactoring the codebase to construct Go errors in the autogenerated code.

Fixes #231.

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Review by mertakman — APPROVED** [review]

File: cmd/mkcgo/generate.go [hunk 1]
```diff
@@ -56,10 +69,13 @@ func generateGo(src *mkcgo.Source, w io.Writer) {
 		fmt.Fprintf(w, "}\n\n")
 	}
 
-	typedefs := make(map[string]string, len(src.TypeDefs))
-	for _, def := range src.TypeDefs {
-		typedefs[def.Name] = def.Type
-	}
+	// Generate error wrapper noescape function, which hides the
+	// error state pointer from the Go garbage collector.
```
Comment (dagood) [inline cmd/mkcgo/generate.go:50]: Maybe link another use of this to make it obvious that it's a known way to do this and it's not something that Go will get wise to. 😄 (Could alternatively `linkname` it?)

```suggestion
	// error state pointer from the Go garbage collector.
	// An instance of https://github.com/golang/go/blob/d704ef76068eb7da15520b08dc7df98f45f85ffa/src/runtime/stubs.go#L194-L201
```

File: cmd/mkcgo/generate.go [hunk 2]
```diff
@@ -492,3 +534,34 @@ func join(ps []*mkcgo.Param, fn func(int, *mkcgo.Param) string, sep string) stri
 	}
 	return strings.Join(params, sep)
 }
+
+const errStateNoEscapeName = "mkcgoNoEscape"
+const errStateStructName = "mkcgo_err_state"
```
Comment (dagood) [inline cmd/mkcgo/generate.go]: Naming nit: at first glance these look like error values with that `err` prefix. Maybe `mkcgoErrState` for consistency, or `errorState`?

File: go_ossl_error.h [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+			errs->code[i] = ERR_get_error_all(&file, &errs->line[i], NULL, NULL, NULL);
+		} else {
+			// OpenSSL 1 error handling
+			errs->code[i] = ERR_get_error_line(&file, &errs->line[i]);
+		}
+		if (errs->code[i] == 0) {
+			break;
+		}
+		if (file != NULL) {
+			// Copy the file name as the pointer we just retrieved will by OpenSSL
```
Comment (dagood) [inline go_ossl_error.h]: A few missing words? My guess:

```suggestion
			// Copy the file name as the pointer we just retrieved will be freed by OpenSSL
```

File: go_ossl_error.h [hunk 4]
```diff
@@ -0,0 +1,78 @@
+#ifndef GO_OSSL_ERROR_H // only include this header once
+#define GO_OSSL_ERROR_H
+
+#include <shims.h>
+#include <stdlib.h> // for free()
+#include <string.h> // for strdup()
+
+int OPENSSL_version_major_Available();
```
Comment (dagood) [inline go_ossl_error.h]: It seems like at some point making a `zossl.h` file would make sense, or manually-maintained forward decls might build up. Maybe add a note in mkcgo about the reason for going with forward decls for future reference?

File: go_ossl_error.h [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+	ERR_clear_error();
+}
+
+// mkcgo_err_retrieve retrieves the error state from OpenSSL.
+// It returns a pointer to a mkcgo_err_state structure
+// that contains the error codes, lines, and file names.
+// The caller is responsible for freeing the memory
+// by calling mkcgo_err_free.
+static mkcgo_err_state *mkcgo_err_retrieve() {
+	mkcgo_err_state *errs = (mkcgo_err_state *)malloc(sizeof(mkcgo_err_state));
```
Comment (dagood) [inline go_ossl_error.h]: Maybe use `calloc` to avoid the zeroing loop?

Or: use `malloc`, but remove the zeroing loop and instead make sure the single `for (int i = 0; i < ERR_NUM_MAX; i++) {` loop ends up assigning every element/field rather than `break`ing. (Or something similar.)

File: hash.go [hunk 6]
```diff
@@ -374,8 +381,9 @@ func (h *evpHash) BlockSize() int {
 func (h *evpHash) Sum(in []byte) []byte {
 	h.init()
 	out := make([]byte, h.Size(), maxHashSize) // explicit cap to allow stack allocation
-	if C.go_hash_sum(h.ctx, h.ctx2, (*C.uchar)(unsafe.SliceData(out))) != 1 {
-		panic(newOpenSSLError("go_hash_sum"))
+	var _err *C.mkcgo_err_state
+	if C.go_hash_sum(h.ctx, h.ctx2, (*C.uchar)(unsafe.SliceData(out)), &_err) != 1 {
+		panic(newMkcgoErr("EVP_DigestFinal_ex", _err))
```
Comment (dagood) [inline hash.go]: This might be an error for either `EVP_MD_CTX_copy` or `EVP_DigestFinal_ex`, right? Not sure how important it is for this particular string to be accurate, but maybe the more generic name is better to avoid potentially being misleading?

Comment (dagood) [inline hash.go]: `errst` to match what `newMkcgoErr` calls it? `_` prefix seems unusual in hand-written Go.

```suggestion
	var errst *C.mkcgo_err_state
	if C.go_hash_sum(h.ctx, h.ctx2, (*C.uchar)(unsafe.SliceData(out)), &errst) != 1 {
		panic(newMkcgoErr("EVP_DigestFinal_ex", errst))
```

File: openssl.go [hunk 7]
```diff
@@ -268,35 +269,50 @@ func base(b []byte) *byte {
...
+	for i := range 16 {
+		e := uint32(errst.code[i])
 		if e == 0 {
 			break
 		}
 		b.WriteByte('\n')
 		var buf [256]byte
 		go_openssl_ERR_error_string_n(e, base(buf[:]), len(buf))
-		b.WriteString(string(buf[:]) + "\n\t" + C.GoString((*C.char)(unsafe.Pointer(file))) + ":" + strconv.Itoa(int(line)))
+		b.Write(buf[:])
```
Comment (dagood) [inline openssl.go]: Maybe fix null terminator handling in buf while here?

```suggestion
		if termIdx := bytes.IndexByte(buf[:], 0); termIdx != -1 {
			b.Write(buf[:termIdx])
		} else {
			b.Write(buf[:])
		}
```

(Brief mention in https://github.com/golang-fips/openssl/issues/266.)

File: openssl_test.go [hunk 8]
```diff
@@ -146,3 +147,45 @@ func TestFIPSCapable(t *testing.T) {
...
+	for range 10 {
+		wg.Add(2)
+		go func() {
+			defer wg.Done()
+			_, _, _, _, _, _, _, _, err := openssl.GenerateKeyRSA(1)
+			if err == nil {
+				t.Error("expected error, got nil")
+			} else if !strings.Contains(err.Error(), "key size too small") {
+				t.Errorf("expected error to contain 'rsa routines', got %q", err)
+			}
```
Comment (dagood) [inline openssl_test.go:168]: Maybe also check that `err.Error()` doesn't contain null bytes, for easy coverage?

**Review by dagood — APPROVED** [review]
Nice! A small handful of minor suggestions.

File: cmd/mkcgo/generate.go (hunk 1 above)
Comment (qmuntal) [reply cmd/mkcgo/generate.go:50]: > (Could alternatively linkname it?)

The `linkname` directive is locked down, better avoid it: https://github.com/golang/go/issues/67401.

File: cmd/mkcgo/generate.go (hunk 2 above)
Comment (qmuntal) [reply cmd/mkcgo/generate.go]: Good point. Will do.

File: go_ossl_error.h (hunk 5 above)
Comment (qmuntal) [reply go_ossl_error.h]: `calloc` 👍

File: openssl_test.go (hunk 8 above)
Comment (qmuntal) [reply openssl_test.go:168]: Good call. Done.

File: go_ossl_error.h (hunk 4 above)
Comment (qmuntal) [reply go_ossl_error.h]: Good point. I've updated `mkcgo` to also generate `zossl.h`, which also enabled other simplifications.

File: hash.go (hunk 6 above)
Comment (qmuntal) [reply hash.go]: Fixed.

**Review by dagood — APPROVED** [review]
