### PR TITLE
Return nil in NewHMAC if HMAC doesn't support the hash function

### LINKED ISSUE #153: NewHMAC panics if the HMAC doesn't support a valid digest
The `hmac.New` function falls back to Go crypto when it is called with a hash function not supported by BoringCrypto's HMAC implementation. This is is signaled by making the bindings return a nil hasher: https://github.com/golang/go/blob/fc9f02c7aec81bcfcc95434d2529e0bb0bc03d66/src/crypto/hmac/hmac.go#L135

We tried to replicate the same behavior in `openssl.NewHMAC`:

https://github.com/golang-fips/openssl/blob/f8eea431f613cac3064280dbb97d9ce1a39de973/hmac.go#L25-L30

The problem is that some OpenSSL providers return a valid hasher that can't be used as a HMAC hasher. An example is the [SymCrypt-OpenSSL](https://github.com/microsoft/SymCrypt-OpenSSL) provider, which doesn't implement HMAC-SHA224 (see test failure below).

We should instruct `openssl.NewHMAC` to return a nil HMAC object when that happens. 

```cmd
go test -run TestHMAC/sha224
Using libcrypto.so.3
OpenSSL version: OpenSSL 3.3.0 9 Apr 2024
FIPS enabled: false
[ERROR] error:41000066:SCOSSL::Algorithm not supported by SCOSSL:SCOSSL does not support hash algorithm for MAC 675 at /usr/src/azl/BUILD/SymCrypt-OpenSSL-1.5.1/ScosslCommon/src/scossl_mac.c, line 193
--- FAIL: TestHMAC (0.00s)
    --- FAIL: TestHMAC/sha224 (0.00s)
panic: EVP_MAC_init failed
openssl error(s):
error:41000066:SCOSSL::Algorithm not supported by SCOSSL
        /usr/src/azl/BUILD/SymCrypt-OpenSSL-1.5.1/ScosslCommon/src/scossl_mac.c:193
error:1C80007D:Provider routines::invalid mode
        /usr/src/azl/BUILD/SymCrypt-OpenSSL-1.5.1/SymCryptProvider/src/mac/p_scossl_hmac.c:164 [recovered]
        panic: EVP_MAC_init failed
openssl error(s):
error:41000066:SCOSSL::Algorithm not supported by SCOSSL
        /usr/src/azl/BUILD/SymCrypt-OpenSSL-1.5.1/ScosslCommon/src/scossl_mac.c:193
error:1C80007D:Provider routines::invalid mode
        /usr/src/azl/BUILD/SymCrypt-OpenSSL-1.5.1/SymCryptProvider/src/mac/p_scossl_hmac.c:164

goroutine 7 [running]:
testing.tRunner.func1.2({0x5b1560, 0xc00002e5b0})
        /usr/lib/golang/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
        /usr/lib/golang/src/testing/testing.go:1634 +0x377
panic({0x5b1560?, 0xc00002e5b0?})
        /usr/lib/golang/src/runtime/panic.go:770 +0x132
github.com/golang-fips/openssl/v2.newHMAC3({0xc000024080, 0x40, 0x40}, {0x63a208, 0xc00010aa50}, 0x7f44a0005bc0)
        /root/openssl/hmac.go:113 +0x345
github.com/golang-fips/openssl/v2.NewHMAC(0xc000118820?, {0x0, 0x0, 0x0})
        /root/openssl/hmac.go:45 +0xac
github.com/golang-fips/openssl/v2.TestHMAC.func1(0xc000118820)
        /root/openssl/hmac_test.go:24 +0x4a
testing.tRunner(0xc000118820, 0xc000038140)
        /usr/lib/golang/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 6
        /usr/lib/golang/src/testing/testing.go:1742 +0x390
exit status 2
FAIL    github.com/golang-fips/openssl/v2       0.009s
```

### PR DESCRIPTION
**Pull request by qmuntal**
This PR adds a check in the OpenSSL 3 `NewHMAC` code path to prove that the fetched HMAC can be used with the given hash function. If that's not possible, then `NewHMAC` will return `nil`. Note that this was already the case if the hash function was not supported as a stand-alone algorithm.

Fixes #153.

### CODE REVIEW

**Comment by qmuntal** [comment]
CI fails because `sync.OnceValue` is not supported in Go 1.20. Will be fixed by #160.

**Comment by karianna** [comment]
#160 has merged, not sure how you re-trigger CI here though

**Comment by qmuntal** [comment]
> https://github.com/golang-fips/openssl/pull/160 has merged, not sure how you re-trigger CI here though

I've now merged `v2` into the PR branch, which re-triggered CI.

File: hmac.go [hunk 1]
```diff
@@ -67,50 +77,84 @@ type opensslHMAC struct {
...
 	}
 	defer C.go_openssl_OSSL_PARAM_BLD_free(bld)
 	C.go_openssl_OSSL_PARAM_BLD_push_utf8_string(bld, paramDigest, digest, 0)
-	params := C.go_openssl_OSSL_PARAM_BLD_to_param(bld)
+	return C.go_openssl_OSSL_PARAM_BLD_to_param(bld)
+}
+
+func isHMAC3DigestSupported(digest string) bool {
+	if _, ok := hmacDigestsSupported.Load(digest); ok {
+		return true
```
Comment (dagood) [inline hmac.go:114]: Should return the value:

```suggestion
	if v, ok := hmacDigestsSupported.Load(digest); ok {
		return v.(bool)
```

I made this change to `TestHMAC` to try it out in `mcr.microsoft.com/oss/go/microsoft/golang:1.23-azurelinux3.0`:

```go
			h := NewHMAC(tt.fn, nil)
			if h == nil {
				h = NewHMAC(tt.fn, nil)
				if h == nil {
					t.Skip("not supported")
				}
			}
```

**Review by karianna — APPROVED** [review]

File: hmac.go (hunk 1 above)
Comment (qmuntal) [reply hmac.go:114]: Wops, good catch.

**Review by dagood — APPROVED** [review]

**Comment by karianna** [comment]
@qmuntal will need a rebase now
